package com.apple.springboot.index.mapper;

import com.apple.springboot.index.entity.TestTable;
import com.apple.springboot.index.entity.TestTableExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TestTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table
     *
     * @mbg.generated Sat Mar 02 12:31:52 CST 2019
     */
    long countByExample(TestTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table
     *
     * @mbg.generated Sat Mar 02 12:31:52 CST 2019
     */
    int deleteByExample(TestTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table
     *
     * @mbg.generated Sat Mar 02 12:31:52 CST 2019
     */
    int deleteByPrimaryKey(Integer idTestTable);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table
     *
     * @mbg.generated Sat Mar 02 12:31:52 CST 2019
     */
    int insert(TestTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table
     *
     * @mbg.generated Sat Mar 02 12:31:52 CST 2019
     */
    int insertSelective(TestTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table
     *
     * @mbg.generated Sat Mar 02 12:31:52 CST 2019
     */
    List<TestTable> selectByExample(TestTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table
     *
     * @mbg.generated Sat Mar 02 12:31:52 CST 2019
     */
    TestTable selectByPrimaryKey(Integer idTestTable);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table
     *
     * @mbg.generated Sat Mar 02 12:31:52 CST 2019
     */
    int updateByExampleSelective(@Param("record") TestTable record, @Param("example") TestTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table
     *
     * @mbg.generated Sat Mar 02 12:31:52 CST 2019
     */
    int updateByExample(@Param("record") TestTable record, @Param("example") TestTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table
     *
     * @mbg.generated Sat Mar 02 12:31:52 CST 2019
     */
    int updateByPrimaryKeySelective(TestTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table
     *
     * @mbg.generated Sat Mar 02 12:31:52 CST 2019
     */
    int updateByPrimaryKey(TestTable record);
}