package com.apple.springboot.index.mapper;

import com.apple.springboot.index.entity.TestTable;
import org.springframework.stereotype.Repository;

@Repository
public interface TestTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table
     *
     * @mbg.generated Sat Mar 02 12:10:10 CST 2019
     */
    int deleteByPrimaryKey(Integer idTestTable);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table
     *
     * @mbg.generated Sat Mar 02 12:10:10 CST 2019
     */
    int insert(TestTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table
     *
     * @mbg.generated Sat Mar 02 12:10:10 CST 2019
     */
    int insertSelective(TestTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table
     *
     * @mbg.generated Sat Mar 02 12:10:10 CST 2019
     */
    TestTable selectByPrimaryKey(Integer idTestTable);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table
     *
     * @mbg.generated Sat Mar 02 12:10:10 CST 2019
     */
    int updateByPrimaryKeySelective(TestTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table
     *
     * @mbg.generated Sat Mar 02 12:10:10 CST 2019
     */
    int updateByPrimaryKey(TestTable record);
}